# Generated by Django 4.0.5 on 2023-03-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_candidate_gender_alter_company_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=50)),
                ('industry', models.CharField(choices=[('Architechture/ Interior Designing', 'Architechture/ Interior Designing'), ('IT & Telecommunication', 'IT & Telecommunication'), ('Teaching/ Education', 'Teaching/ Education'), ('NGO/ INGO', 'NGO/ INGO'), ('Graphics/ Designing', 'Graphics/ Designing'), ('Hospitality', 'Hospitality'), ('Sales/ Public Relation', 'Sales/ Public Relation'), ('Legal Services', 'Legal Services'), ('Other', 'Other')], default='Other', max_length=200, verbose_name='Industry')),
                ('description', models.CharField(blank=True, max_length=900, null=True)),
                ('job_type', models.CharField(choices=[('On-Site', 'On-Site'), ('Remote', 'On-Site'), ('Hybrid', 'Hybrid')], default='On-Site', max_length=200, verbose_name='Status')),
                ('status', models.BooleanField(default=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
            ],
        ),
    ]
