# Generated by Django 4.0.5 on 2023-03-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobroles_jobrequirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='description',
        ),
        migrations.AddField(
            model_name='jobs',
            name='level',
            field=models.CharField(default='Junior', max_length=15),
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.CharField(default='Negotiable', max_length=20),
        ),
    ]
