# Generated by Django 4.0.5 on 2023-05-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='level',
            field=models.CharField(choices=[('Senior', 'Senior'), ('Mid-level', 'Mid-level'), ('Junior', 'Junior')], default='Junior', max_length=200, verbose_name='Level'),
        ),
    ]
