# Generated by Django 4.0.5 on 2023-03-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('Architechture/ Interior Designing', 'Architechture/ Interior Designing'), ('IT & Telecommunication', 'IT & Telecommunication'), ('Teaching/ Education', 'Teaching/ Education'), ('NGO/ INGO', 'NGO/ INGO'), ('Graphics/ Designing', 'Graphics/ Designing'), ('Hospitality', 'Hospitality'), ('Sales/ Public Relation', 'Sales/ Public Relation'), ('Legal Services', 'Legal Services'), ('Other', 'Other')], default='Other', max_length=200, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
