# Generated by Django 4.0.5 on 2023-03-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_candidate_gender_alter_company_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
