# Generated by Django 4.0.5 on 2023-03-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_company_website_company_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='year',
            new_name='est_year',
        ),
    ]
