# Generated by Django 3.2.7 on 2023-04-08 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_year_company_est_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='preference',
            field=models.CharField(choices=[('Architechture/ Interior Designing', 'Architechture/ Interior Designing'), ('IT & Telecommunication', 'IT & Telecommunication'), ('Teaching/ Education', 'Teaching/ Education'), ('NGO/ INGO', 'NGO/ INGO'), ('Graphics/ Designing', 'Graphics/ Designing'), ('Hospitality', 'Hospitality'), ('Sales/ Public Relation', 'Sales/ Public Relation'), ('Legal Services', 'Legal Services'), ('Other', 'Other')], default='Other', max_length=200, verbose_name='Preference'),
        ),
        migrations.AddField(
            model_name='company',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Job Banner', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=8, verbose_name='Gender'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=25)),
                ('job_title', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('start_year', models.CharField(max_length=4)),
                ('end_year', models.CharField(max_length=4, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('start_year', models.CharField(max_length=4)),
                ('end_year', models.CharField(max_length=4, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
