# Generated by Django 3.2.7 on 2023-04-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230408_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Job Banner', null=True, upload_to='images/user/company'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='display_picture',
            field=models.ImageField(blank=True, help_text='Display picture containing a person or a logo.', null=True, upload_to='images/user'),
        ),
    ]
