# Generated by Django 4.0.5 on 2023-05-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_usertokens_preference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTokens',
            new_name='NotificationToken',
        ),
    ]
