# Generated by Django 4.0.5 on 2023-05-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_usertokens_notificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtoken',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
