# Generated by Django 4.0.5 on 2023-05-25 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_notificationtoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, max_length=20, null=True)),
                ('job_level', models.CharField(choices=[('Senior', 'On-Site'), ('Mid-Level', 'Mid-Level'), ('Junior', 'Junior')], default='Junior', max_length=200, verbose_name='Level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
